### ISSUE TITLE
UASTC test

### ISSUE THREAD

**Issue by slimbuck** [BinomialLLC/basis_universal#131]
Hi @richgel999 ,

Quality-wise we struggle most with normal maps under basis compression. We swizzle normal maps to GGGR as suggested, however the quality of the resulting GGG channel on iOS is so poor that we have chosen to transcode to RGBA8 instead of PVRTC. (The alpha R channel is fine).

We were hoping uastc would improve on this, but from a quick test on one of our difficult cases I don't see substantial improvement. In fact the resulting GGG data for both etc1 and uastc are very similar.

Am I right to conclude that in general switching to uastc won't improve quality of PVRTC?

Also, am I right in saying that an etc1 basis image will generally have higher resulting quality than a uastc basis file transcoded to etc1?

Thanks!

**Comment by richgel999** [comment]
> Am I right to conclude that in general switching to uastc won't improve quality of PVRTC?

Both ETC1S and UASTC transcoders use basically the same routine to pack PVRTC1 texture data on the fly. I have prototyped several improvements to this function, but I haven't gotten them in yet (partially because they are slower and more complex). The current method is the lowest quality format we support. Sorry I don't have a better answer at the moment. PVRTC1 is a very difficult format to encode to in real-time at high quality.

- Also, am I right in saying that an etc1 basis image will generally have higher resulting quality than a uastc basis file transcoded to etc1?

No, UASTC->ETC1 is in many (but not all) cases higher quality than ETC1S. UASTC->ETC1 supports 2x4/4x2 subblocks, and ETC1S doesn't. This means each 4x4 ETC1 block can have 2 colors in UASTC mode, but only one color in ETC1S mode. Also UASTC->ETC1 supports both "individual" and "differential" encoding modes.

On the flip side, the UASTC->ETC1 transcoder uses a real-time method to compute the subblock colors. We store hints to improve it, but sometimes the results can be a little more banded than the highest quality ETC1S equivalent. You really need to experiment with your texture data to determine which format is best, but in general UASTC should be higher quality. (I'll post benchmarks of this to the wiki in the future.)

**Comment by slimbuck** [comment]
Hi @richgel999,

Thanks for the info. After some testing I found that UASTC resulted in slightly higher ETC1 quality, as you say.

Unfortunately PVRTC remains the biggest issue for us. Hopefully apple will one day expose ASTC in browser.
