### ISSUE TITLE
Simplify solid-color BC7 transcoding 

### ISSUE THREAD

**Issue by lexaknyazev** [BinomialLLC/basis_universal#160]
The spec and the source code suggest trying to use BC7 mode 6 first. However, the `g_bc7_mode_5_optimal_endpoints` array has zero errors for all 256 values, thus always providing lossless results.

@richgel999 could you please verify?

**Comment by richgel999** [comment]
One thing the spec doesn't mention is the output data entropy of the UASTC data, which (all other things being equal) we want to reduce. Using BC7 mode 6 first (over mode 5) is preferred because it's more commonly used across a wide range of textures. An LZ codec would be able to squeeze more bits from the solid color blocks if they used mode 6 vs. 5. 

Does this make sense? 

![image](https://user-images.githubusercontent.com/6934809/87955051-36f47500-ca7b-11ea-9a7e-9445e81bbabf.png)

**Comment by lexaknyazev** [comment]
Sorry, I'm not following. The transcoder's output is supposed to be uploaded to the GPU. How is LZ relevant there?

**Comment by richgel999** [comment]
Because one additional use case of Basis Universal UASTC (that we definitely want to preserve, although this is likely not useful or interesting for KTX2 purposes) is to encode to RDO UASTC, then immediately transcode that to plain ASTC or BC7 and ship that data (which gets compressed with LZ). The more mode 6 gets used, the better for this use case.

**Comment by richgel999** [comment]
I've updated the spec with a note about this. I'll spend more time on this later today or tomorrow. Thanks for pointing it out.

**Comment by lexaknyazev** [comment]
> The more mode 6 gets used, the better for this use case.

Thanks for the clarification. I wasn't aware of such use case.

> A transcoder that is only intended for the common use case (upload to GPU) can do whatever it wants on solid color blocks, as long as the errors are the same.

Looking again at the source code, it seems that the final error is always 0. The only difference is that mode 5 is used only when the error is non-zero with mode 6. So we could always require lossless transcoding of solid blocks.

**Comment by richgel999** [comment]
> So we could always require lossless transcoding of solid blocks.

Yes, exactly. I'll update the spec.

**Comment by richgel999** [comment]
I've updated the spec to clarify that you can always use mode 5. Thanks a lot!

**Comment by lexaknyazev** [comment]
It turns out that BC7 mode 5 endpoints could be computed like this, without any loops:
```
e_lo = color >> 1;
e_hi = (color >> 1) + (color & 1) - (color >> 7);
```

**Comment by richgel999** [comment]
Nice - thanks for this! When I do another pass on the transcoder, I'll integrate this.
