### ISSUE TITLE
Add support for transparency for pvrtc1 and pvrtc1 2bpp

### ISSUE THREAD

**Issue by mihaisebea** [BinomialLLC/basis_universal#19]
Hi,
I know this is on the todo list, I'm just filing this here in case someone has time to work on it.
@richgel999 could you comment a bit with what would be needed for this and how would we go about  implementing it ?

**Comment by richgel999** [comment]
Hi - Yes this is coming soon (Google announced this as part of the next release). 
For PVRTC1 4bpp, I was planning on taking the current transcoder and adding either punch-through alpha, full alpha support, or maybe even both because I can see use cases for each in PVRTC1. 
I was going to first try taking the current algorithm and modifying it for alpha, just by extending it. If the quality was acceptable, I was going to ship that. I expect there to be more banding with full-alpha, but I don't know if the level of banding will be unacceptable.
The current algorithm is pretty simple at its core: The endpoints are computed from the RGB bounding boxes of the colors in each block, with proper rounding. The modulation values are computed by interpolating the endpoints in a scaled luma space, and determining which modulation value to use for each pixel with some simple compares. This all can be expanded to do alpha too, but it'll be some surgery. 
For PVRTC1 2bpp, it's more complex because the blocks aren't 4x4 pixels. I don't know if computing the modulation values using just luma would work/look good, so that may need to be changed to vector.
For a good reference with code see: 
http://roartindon.blogspot.com/2014/08/pvr-texture-compression-exploration.html
https://bitbucket.org/jthlim/pvrtccompressor
This method computes the modulation values differently than basisu, but it's overall similar. The major differences: basisu converts ETC1S data to PVRTC1, and computes the modulation values in luma space. Lim's encoder does the work starting from full RGB(A) pixels and computes the modulation values in RGB(A) space.

**Comment by richgel999** [comment]
Okay, I have an implementation ready, and it'll be in the next release.

**Comment by richgel999** [comment]
Support for PVRTC1 RGBA is in. I also have a solution for PVRTC2 that results in better quality, which will be checked in this week sometime.
