### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by alexmyczko** [BinomialLLC/basis_universal#353]
would you consider renaming the project?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038205

let me recommend a new name:
not-so-base-neither-universal

**Comment by playmer** [comment]
I don't really see how `basis_` could be confused with `base-`, but shouldn't the Debian maintainers (of which you seem to be among) come up with an appropriate prefix/postfix? 

It seems like a little much to ask the project to fully change it's name rather than simply adjust the package name if it's such an issue for debian.

**Comment by alexmyczko** [comment]
You’re right was looking for suggestions of names but will try come up with one myself. Main issue is if everyone does you need to namespace consolidate them on repology.
