### ISSUE TITLE
Polyfill for browsers without WASM support?

### ISSUE THREAD

**Issue by Ben-Mack** [BinomialLLC/basis_universal#53]
Is it possible to support browser without WASM support?

According to the [wasm compatibility chart](https://caniuse.com/#search=wasm), there're still majority of devices doesn't support WASM yet (like Safari below iOS 11).

I think to be more "Universal", Basis should provide some kind of polyfill for browser without WASM support (I guess decoding could be slower, but slower is still better than none right?)

**Comment by donmccurdy** [comment]
It is possible to slightly modify the emscripten build (https://github.com/BinomialLLC/basis_universal/tree/master/webgl/transcoder) to compile to JS instead of WASM. There are other reasons that developers may want to compile different versions of the transcoder, so I don't know whether multiple versions of the transcoder should be provided _by this repository_, but feel free to have a go at recompiling it and let us know how it goes!
