### ISSUE TITLE
sRGB and SNORM formats

### ISSUE THREAD

**Issue by DeanoC** [BinomialLLC/basis_universal#66]
AFAICT tell there no infomation about wether the texture is in sRGB space or SNORM (for BC4/BC5).

Essentially we have to keep that metadata in the file name or some where else.

Would be good to store that data in the basis file itself

**Comment by richgel999** [comment]
Yes - agreed. We are adding a new flag to the .basis file header, "cBASISHeaderFlagSRGB". 

I asked a bunch of app developers about this, and in most cases they always store extra metadata about the texture anyway. Or they know which ones will need to be SRGB read or not. So it's unclear how important this actually is.

**Comment by richgel999** [comment]
Also, please note that it's possible to store up to 64-bits of user defined data in every basis file. So you could just add a flag in yourself. (But we'll add an "official" flag.)

**Comment by mosra** [comment]
Possibly related -- together with a sRGB bit, could the file contain also "official" information about how many input channels (1, 2, 3, 4) was each image created from? The use case is again general image import / viewing where you control just the "consumer" part of the pipeline and don't know what's in given file and how to treat it (and thus you can't use custom data to store that, either).

There's the alpha bit already, so that one could be expanded to give channel count info.

**Comment by malytomas** [comment]
I second both of these ideas: srgb flag and number of channels.

**Comment by richgel999** [comment]
We've added support for the KTX2 file format to the repo, which contains this information. Let me know if this is enough. For now, I'm closing this, but feel free to reopen if you think this isn't enough.
