### ISSUE TITLE
Extremely slow, even on lowest quality

### ISSUE THREAD

**Issue by reduz** [BinomialLLC/basis_universal#75]
A setting where compression speed is priority over file size and quality would be very desired, so at least the files can be imported first like this and then get properly compressed on background.

Right now compression times for 128x128 files are about 5 seconds on lowest quality (0), vs 2/3 milliseconds for a S3TC or ETC compressor.

**Comment by reduz** [comment]
Some numbers for reference:

This is a 128x128 texture.

```
$ basisu -q 0 -comp_level 0 pepeche.png
Compression succeeded to file "pepeche.basis" in 5.381 secs

(I tried all the options, this is the fastest i could get it)

vs

$ time etc1tool pepeche.png 

real	0m0,011s
user	0m0,008s
sys	0m0,004s
```

Either I am doing something very wrong, or Basis Universal seems like it can only be useful to leave a project building for deploy over the weekend. Importing a project for me takes forever.

**Comment by reduz** [comment]
Attaching the file I used for reference, but seems to be the same with anything I throw at it.

[pepeche.zip](https://github.com/BinomialLLC/basis_universal/files/3660687/pepeche.zip)

**Comment by richgel999** [comment]
On my really old Core i7 laptop (2.2 GHz, 4 cores), under Win10 x64, I get 2.6 secs to compress a 512x768 texture with mipmaps at default settings (comp_level 1 quality 128). (See below.) At comp_level 0 I get 1.308 secs. Not sure why you are seeing such different performance - but something may be wrong. 

Also, basisu doesn't claim to use ETC1. It uses ETC1S, a subset of ETC1. See the method basisu_lowlevel_transcoder::transcode_slice() and study how it decodes the ETC1S endpoints/selectors if you want to see the transcoder's key inner loop. This technology is basically like my old "crunch" library, except it uses ETC1S, has a stronger encoder and compressed file format, and it has transcoders that can convert ETC1S to any texture format.

The encoder does a lot more heavy lifting than a plain ETC1 encoder, because it has to quantize the endpoints/selectors of all the blocks in a way that doesn't destroy the texture, and it must compress the output. 

C:\dev\basis_universal_rel_m4\basis_universal\bin>basisu  c:\dev\test_images\photo_png\kodim18.png -mipmap
Basis Universal GPU Texture Compressor Reference Encoder v1.09.00, Copyright (C) 2019 Binomial LLC, All rights reserved
Processing 1 total files
Read source image "c:\dev\test_images\photo_png\kodim18.png", 512x768
Total basis file slices: 10
Slice: 0, alpha: 0, orig width/height: 512x768, width/height: 512x768, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
Slice: 1, alpha: 0, orig width/height: 256x384, width/height: 256x384, first_block: 24576, image_index: 0, mip_level: 1, iframe: 0
Slice: 2, alpha: 0, orig width/height: 128x192, width/height: 128x192, first_block: 30720, image_index: 0, mip_level: 2, iframe: 0
Slice: 3, alpha: 0, orig width/height: 64x96, width/height: 64x96, first_block: 32256, image_index: 0, mip_level: 3, iframe: 0
Slice: 4, alpha: 0, orig width/height: 32x48, width/height: 32x48, first_block: 32640, image_index: 0, mip_level: 4, iframe: 0
Slice: 5, alpha: 0, orig width/height: 16x24, width/height: 16x24, first_block: 32736, image_index: 0, mip_level: 5, iframe: 0
Slice: 6, alpha: 0, orig width/height: 8x12, width/height: 8x12, first_block: 32760, image_index: 0, mip_level: 6, iframe: 0
Slice: 7, alpha: 0, orig width/height: 4x6, width/height: 4x8, first_block: 32766, image_index: 0, mip_level: 7, iframe: 0
Slice: 8, alpha: 0, orig width/height: 2x3, width/height: 4x4, first_block: 32768, image_index: 0, mip_level: 8, iframe: 0
Slice: 9, alpha: 0, orig width/height: 1x1, width/height: 4x4, first_block: 32769, image_index: 0, mip_level: 9, iframe: 0
Wrote output .basis file "kodim18.basis"
Compression succeeded to file "kodim18.basis" in 2.556 secs

![laptop_cpu](https://user-images.githubusercontent.com/6934809/65740312-177bfe00-e09d-11e9-98bd-a0cd9190f888.png)

**Comment by richgel999** [comment]
OK - I see the problem!
 
As this is a small texture, the encoder automatically switches to use global selector palettes, for smaller files. If you run with -debug, you'll see a series of these messages printed to stdout:

Global selector palette optimization: 25.3% complete
...

If you encode with "-no_auto_global_sel_pal", it encodes in around .3 secs:

C:\dev\basis_universal_rel_m4\basis_universal\bin>basisu  c:\dev\test_images\pepeche.png  -no_auto_global_sel_pal
Basis Universal GPU Texture Compressor Reference Encoder v1.09.00, Copyright (C) 2019 Binomial LLC, All rights reserved
Processing 1 total files
Read source image "c:\dev\test_images\pepeche.png", 128x128
Total basis file slices: 1
Slice: 0, alpha: 0, orig width/height: 128x128, width/height: 128x128, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
Wrote output .basis file "pepeche.basis"
Compression succeeded to file "pepeche.basis" in 0.243 secs

C:\dev\basis_universal_rel_m4\basis_universal\bin>basisu  c:\dev\test_images\pepeche.png  -no_auto_global_sel_pal -mipmap
Basis Universal GPU Texture Compressor Reference Encoder v1.09.00, Copyright (C) 2019 Binomial LLC, All rights reserved
Processing 1 total files
Read source image "c:\dev\test_images\pepeche.png", 128x128
Total basis file slices: 8
Slice: 0, alpha: 0, orig width/height: 128x128, width/height: 128x128, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
Slice: 1, alpha: 0, orig width/height: 64x64, width/height: 64x64, first_block: 1024, image_index: 0, mip_level: 1, iframe: 0
Slice: 2, alpha: 0, orig width/height: 32x32, width/height: 32x32, first_block: 1280, image_index: 0, mip_level: 2, iframe: 0
Slice: 3, alpha: 0, orig width/height: 16x16, width/height: 16x16, first_block: 1344, image_index: 0, mip_level: 3, iframe: 0
Slice: 4, alpha: 0, orig width/height: 8x8, width/height: 8x8, first_block: 1360, image_index: 0, mip_level: 4, iframe: 0
Slice: 5, alpha: 0, orig width/height: 4x4, width/height: 4x4, first_block: 1364, image_index: 0, mip_level: 5, iframe: 0
Slice: 6, alpha: 0, orig width/height: 2x2, width/height: 4x4, first_block: 1365, image_index: 0, mip_level: 6, iframe: 0
Slice: 7, alpha: 0, orig width/height: 1x1, width/height: 4x4, first_block: 1366, image_index: 0, mip_level: 7, iframe: 0
Wrote output .basis file "pepeche.basis"
Compression succeeded to file "pepeche.basis" in 0.298 secs

**Comment by richgel999** [comment]
The global selector palette stuff was intended for icons and very small textures. It reduces the size of the codebooks. However, it can be safely disabled (-no_auto_global_sel_pal or set m_no_auto_global_sel_pal to false) if the encoding time is unacceptable.  

It's a classic size vs. compression time tradeoff. Some of our largest corporate users throw literally an entire city's worth of machines at compressing images, so it can be difficult to come up with one set of encoder options which make everyone happy.

**Comment by fire** [comment]
```
basisu_v1_08> .\basisu.exe -q 0 -no_auto_global_sel_pal  ..\pepeche\pepeche.png              Basis Universal GPU Texture Compressor Reference Encoder v1.08.00, Copyright (C) 2017-2019 Binomial LLC, All rights reserved
Processing 1 total files
Read source image "..\pepeche\pepeche.png", 128x128
Total basis file slices: 1
Slice: 0, alpha: 0, orig width/height: 128x128, width/height: 128x128, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
Wrote output .basis file "pepeche.basis"
Compression succeeded to file "pepeche.basis" in 0.191 secs
```

**Comment by reduz** [comment]
Oh yes, indeed, disabling this option boosted performance hugely, it seems to be very usable now, thanks a lot!

**Comment by punto-** [comment]
This option (m_no_auto_global_sel_pal) seems to have gone away from the params structure in the current master, do the new defaults include this behavior? I having issues with slow compression as well, I'd like to make sure I'm using this correctly

**Comment by lihongyi1234** [comment]
i have the same problem, compress speed is much important for me ,when i compress texture with resolution 2048*2048, it takes about 10 seconds for just one picture, then i look into the basis project ,i find functions  process_frontend() and process_backend() wasting too much time ,why is that happens, what should i do to make is quickly,thanks
